version: '3.8'
services:
  db:
    image: mysql:8.0
    volumes:
      - 'db_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-school_diary_table_app_${RAILS_ENV}}
      MYSQL_USER: ${MYSQL_USER:-school_diary_table_app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  web:
    build:
      context: .
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_REGION: ${AWS_REGION}
        AWS_BUCKET: ${AWS_BUCKET}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake assets:precompile && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - '.:/rails'  # プロジェクトディレクトリを/railsにマウント
      - './db:/rails/db'  # dbディレクトリを明示的にマウント
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET=${AWS_BUCKET}

volumes:
  db_data:
